SELECT CURRENT_TIMESTAMP;
--CREATE SCHEMA rest;
----DROP TABLE IF EXISTS time_event;
--CREATE TABLE time_event (
--    id INTEGER PRIMARY KEY AUTOINCREMENT,
--    event_date_time DATETIME
--);
--CREATE TABLE time_event (
--    id INT PRIMARY KEY AUTO_INCREMENT,
--    event_date_time DATETIME
--);