spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:;DB_CLOSE_ON_EXIT=TRUE;MODE=Oracle
    username: sa
    password:
  h2:
    console:
      enabled: true
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: -1