spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./target/db/testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: -1